name: Close pull request

on:
  pull_request_target:
    types:
      - opened

jobs:
  close-pr:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - run: gh pr close "$NUMBER" --comment "$COMMENT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.number }}
          COMMENT: >
            Thank you for submitting your pull request.
            Please note that the main repository is located at https://git.naxdy.org/NaxdyOrg/NaxGCC-HW - please submit your pull request there if you would like it to be considered for merging.
